version: '3.3'
services:
  streamer:
    image: rahulbane/azero-streamer:v2.0
    env_file:
      - .env
    ports:
      - '6901:6901'
    depends_on:
      - mongodb
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
  mongodb:
    image: mongo:6-jammy
    command: mongod --port 27018
    ports:
      - '27018:27018'
    volumes:
      - ./db-alpha:/data/db:rw
