version: '3.3'
services:
  streamer:
    image: azero-streamer
    env_file:
      - .env
    ports:
      - '6903:6903'
    depends_on:
      - mongodb
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
  mongodb:
    image: mongo:6-jammy
    command: mongod --port 27018
    ports:
      - '27018:27018'
    volumes:
      - ./db-alpha:/data/db:rw
