replicaCount: 1

app: azero-streamer
env: mainnet

image:
  repository: asia-south1-docker.pkg.dev/router-mainnet-api/router-apps-asia-south/azero-streamer
  tag: latest
  pullPolicy: IfNotPresent

container:
  secretName: azero-streamer-env

service:
  type: NodePort
  name: azero-streamer
  port: 8903
  targetPort: 8903

sslcert:
  enabled: true
  name: "azero-streamer-tls"
  host: "api.azero-streamer.routerchain.network"
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "20"
    "helm.sh/resource-policy": "keep"

autoscaling:
  enabled: true
  targetCPUUtilizationPercentage: 80
  minReplicas: 1
  maxReplicas: 1

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1: "managed-certificates"
    "helm.sh/resource-policy": "keep"

backendConfig:
  healthCheck:
    requestPath: /
    checkIntervalSec: 30
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 2

resources:
  requests:
    memory: "256Mi"
    cpu: "450m"
  limits:
    memory: "400Mi"
    cpu: "650m"
